### model
model_name_or_path: /home/quanzhong/paligemma-3b-pt-448
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
max_grad_norm: 1.0

### dataset
dataset_dir: data
dataset: tongue_train
template: paligemma
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/paligemma-3b-pt-448/1_9/train
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
<<<<<<< HEAD
report_to: all
=======
save_only_model: false
>>>>>>> main

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_steps: 0
bf16: true
ddp_timeout: 180000000
<<<<<<< HEAD
optim: adamw_torch
# deepspeed: examples/deepspeed/ds_z3_config.json
=======
resume_from_checkpoint: null
>>>>>>> main

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### swanlab
use_swanlab: true
swanlab_project: llamafactory
swanlab_run_name: paligemma-3b-pt-448